# -*- coding: utf-8 -*-
"""creditrisk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3oP4fYK5jVlGrLKFfnkke2y7vt6m7HE
"""

"""
Credit Risk Prediction with SHAP Explanations
Uses the Alfazril/credit-risk-prediction ensemble model from Hugging Face
and explains predictions with SHAP visualizations.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap
from huggingface_hub import hf_hub_download
import joblib
import pickle

# Set style for better visualizations
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)

print("="*80)
print("Credit Risk Prediction System with SHAP Explanations")
print("="*80)

# Feature names as specified in the model card
FEATURE_NAMES = [
    'Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
    'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio',
    'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
    'HasDependents', 'LoanPurpose', 'HasCoSigner'
]

print("\nDownloading model from Hugging Face...")
print("Model: Alfazril/credit-risk-prediction")

# Download model files
try:
    # Try to download the ensemble model components
    # Note: Actual file names may vary, adjust as needed
    model_path = hf_hub_download(
        repo_id="Alfazril/credit-risk-prediction",
        filename="credit_risk_xgboost_model.pkl"  # Adjust based on actual files in repo
    )
    print(f"Model downloaded successfully!")
except Exception as e:
    print(f"Note: Could not download model file: {e}")
    print("Creating synthetic model for demonstration purposes...\n")

    # Create a synthetic model for demonstration
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.preprocessing import StandardScaler

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    scaler = StandardScaler()

    # Generate synthetic training data
    np.random.seed(42)
    n_samples = 1000
    X_synthetic = np.random.randn(n_samples, len(FEATURE_NAMES))
    # Create target based on simple rules
    y_synthetic = ((X_synthetic[:, 2] > 0.5) |  # High loan amount
                   (X_synthetic[:, 8] > 0.7) |   # High DTI ratio
                   (X_synthetic[:, 3] < -0.5)).astype(int)  # Low credit score

    X_synthetic_scaled = scaler.fit_transform(X_synthetic)
    model.fit(X_synthetic_scaled, y_synthetic)

    print("Synthetic model created and trained.")

# Create sample credit applications
print("\n" + "="*80)
print("Sample Credit Applications")
print("="*80 + "\n")

sample_data = pd.DataFrame([
    {
        'Age': 35, 'Income': 75000, 'LoanAmount': 25000, 'CreditScore': 720,
        'MonthsEmployed': 48, 'NumCreditLines': 5, 'InterestRate': 6.5,
        'LoanTerm': 60, 'DTIRatio': 0.35, 'Education': 1, 'EmploymentType': 1,
        'MaritalStatus': 1, 'HasMortgage': 1, 'HasDependents': 1,
        'LoanPurpose': 2, 'HasCoSigner': 0
    },
    {
        'Age': 28, 'Income': 45000, 'LoanAmount': 35000, 'CreditScore': 650,
        'MonthsEmployed': 24, 'NumCreditLines': 3, 'InterestRate': 9.5,
        'LoanTerm': 72, 'DTIRatio': 0.55, 'Education': 0, 'EmploymentType': 0,
        'MaritalStatus': 0, 'HasMortgage': 0, 'HasDependents': 0,
        'LoanPurpose': 1, 'HasCoSigner': 0
    },
    {
        'Age': 45, 'Income': 120000, 'LoanAmount': 15000, 'CreditScore': 800,
        'MonthsEmployed': 120, 'NumCreditLines': 8, 'InterestRate': 4.5,
        'LoanTerm': 36, 'DTIRatio': 0.15, 'Education': 2, 'EmploymentType': 1,
        'MaritalStatus': 1, 'HasMortgage': 1, 'HasDependents': 1,
        'LoanPurpose': 0, 'HasCoSigner': 0
    },
    {
        'Age': 32, 'Income': 60000, 'LoanAmount': 40000, 'CreditScore': 580,
        'MonthsEmployed': 18, 'NumCreditLines': 2, 'InterestRate': 12.5,
        'LoanTerm': 84, 'DTIRatio': 0.65, 'Education': 1, 'EmploymentType': 0,
        'MaritalStatus': 0, 'HasMortgage': 0, 'HasDependents': 1,
        'LoanPurpose': 3, 'HasCoSigner': 1
    },
    {
        'Age': 50, 'Income': 95000, 'LoanAmount': 20000, 'CreditScore': 750,
        'MonthsEmployed': 180, 'NumCreditLines': 6, 'InterestRate': 5.5,
        'LoanTerm': 48, 'DTIRatio': 0.25, 'Education': 2, 'EmploymentType': 1,
        'MaritalStatus': 1, 'HasMortgage': 1, 'HasDependents': 0,
        'LoanPurpose': 2, 'HasCoSigner': 0
    }
])

# Display sample applications
print("Applicant Details:")
print("-" * 80)
for idx, row in sample_data.iterrows():
    print(f"\nApplicant {idx + 1}:")
    print(f"  Age: {row['Age']}, Income: ${row['Income']:,}, Loan: ${row['LoanAmount']:,}")
    print(f"  Credit Score: {row['CreditScore']}, DTI Ratio: {row['DTIRatio']:.1%}")
    print(f"  Months Employed: {row['MonthsEmployed']}, Credit Lines: {row['NumCreditLines']}")

# Scale features
X_scaled = scaler.transform(sample_data.values)

# Make predictions
print("\n" + "="*80)
print("Risk Predictions")
print("="*80 + "\n")

predictions = model.predict(X_scaled)
probabilities = model.predict_proba(X_scaled)

for idx, (pred, prob) in enumerate(zip(predictions, probabilities)):
    risk_prob = prob[1] * 100
    if risk_prob < 30:
        risk_level = "LOW RISK"
    elif risk_prob < 60:
        risk_level = "MEDIUM RISK"
    else:
        risk_level = "HIGH RISK"

    print(f"Applicant {idx + 1}:")
    print(f"  Default Risk: {risk_prob:.1f}%")
    print(f"  Classification: {risk_level}")
    print(f"  Decision: {'APPROVED' if pred == 0 else 'DENIED'}")
    print()

# SHAP Analysis
print("="*80)
print("SHAP Analysis - Explaining Model Predictions")
print("="*80 + "\n")

print("Initializing SHAP explainer...")
# Use TreeExplainer for tree-based models
explainer = shap.TreeExplainer(model)

print("Computing SHAP values...")
shap_values = explainer.shap_values(X_scaled)

# If binary classification, get values for positive class (default/risk)
if isinstance(shap_values, list):
    shap_values_risk = shap_values[1]
else:
    shap_values_risk = shap_values

print("Generating SHAP visualizations...\n")

# Visualization 1: Summary plot (beeswarm)
print("1. Summary Plot (Feature Impact Distribution)")
plt.figure(figsize=(12, 8))
shap.summary_plot(shap_values_risk, X_scaled, feature_names=FEATURE_NAMES, show=False)
plt.tight_layout()
plt.savefig('shap_summary_plot.png', dpi=150, bbox_inches='tight')
print("   Saved: shap_summary_plot.png")
plt.close()

# Visualization 2: Bar plot (mean absolute SHAP values)
print("2. Feature Importance Plot")
plt.figure(figsize=(10, 8))
shap.summary_plot(shap_values_risk, X_scaled, feature_names=FEATURE_NAMES,
                  plot_type="bar", show=False)
plt.tight_layout()
plt.savefig('shap_importance_plot.png', dpi=150, bbox_inches='tight')
print("   Saved: shap_importance_plot.png")
plt.close()

# Visualization 3: Waterfall plot for first applicant
print("3. Waterfall Plot (Applicant 1 - Detailed Breakdown)")
plt.figure(figsize=(10, 8))
expected_value = explainer.expected_value
if isinstance(expected_value, list):
    expected_value = expected_value[1] if len(expected_value) > 1 else expected_value[0]
elif hasattr(expected_value, '__len__') and len(expected_value) > 0:
    expected_value = expected_value[0]

# Ensure we're getting a 1D array for single prediction
shap_vals_single = shap_values_risk[0]
if len(shap_vals_single.shape) > 1:
    # If it's 2D (e.g., 16x2), take the second column (risk class)
    shap_vals_single = shap_vals_single[:, 1] if shap_vals_single.shape[1] > 1 else shap_vals_single[:, 0]

shap.waterfall_plot(
    shap.Explanation(
        values=shap_vals_single,
        base_values=expected_value,
        data=X_scaled[0],
        feature_names=FEATURE_NAMES
    ),
    show=False
)
plt.tight_layout()
plt.savefig('shap_waterfall_applicant1.png', dpi=150, bbox_inches='tight')
print("   Saved: shap_waterfall_applicant1.png")
plt.close()

# Visualization 4: Force plot for multiple applicants
print("4. Force Plot (All Applicants)")
try:
    shap.force_plot(
        explainer.expected_value[1] if isinstance(explainer.expected_value, list)
        else explainer.expected_value,
        shap_values_risk,
        X_scaled,
        feature_names=FEATURE_NAMES,
        matplotlib=True,
        show=False
    )
    plt.tight_layout()
    plt.savefig('shap_force_plot.png', dpi=150, bbox_inches='tight')
    print("   Saved: shap_force_plot.png")
    plt.close()
except:
    print("   (Force plot generation skipped - requires JavaScript rendering)")


# Visualization 5: Dependence plot for top features
print("5. Dependence Plots (Top 2 Features)")
feature_importance = np.abs(shap_values_risk).mean(axis=0)
top_features_idx = np.argsort(feature_importance)[-2:].flatten()

print(top_features_idx)

for i, feat_idx in enumerate(top_features_idx):
    try:
        plt.figure(figsize=(10, 6))
        shap.dependence_plot(
            int(feat_idx),
            shap_values_risk,
            X_scaled,
            feature_names=FEATURE_NAMES,
            show=False,
            interaction_index=None  # Disable automatic interaction detection
        )
        plt.tight_layout()
        plt.savefig(f'shap_dependence_{FEATURE_NAMES[feat_idx]}.png', dpi=150, bbox_inches='tight')
        print(f"   Saved: shap_dependence_{FEATURE_NAMES[feat_idx]}.png")
        plt.close()
    except Exception as e:
        print(f"   Could not generate dependence plot for {FEATURE_NAMES[feat_idx]}: {e}")
        plt.close()


# Analysis Summary
print("\n" + "="*80)
print("Key Insights from SHAP Analysis")
print("="*80 + "\n")

# Calculate feature importance
feature_importance_df = pd.DataFrame({
    'Feature': FEATURE_NAMES,
    'Mean_Abs_SHAP': np.abs(shap_values_risk).mean(axis=0)
}).sort_values('Mean_Abs_SHAP', ascending=False)

print("Top 10 Most Important Features:")
print("-" * 60)
for idx, row in feature_importance_df.head(10).iterrows():
    print(f"{row['Feature']:20s} | Importance: {row['Mean_Abs_SHAP']:.4f}")

# Analyze individual predictions
print("\n" + "="*80)
print("Individual Applicant Analysis")
print("="*80)

for i in range(len(sample_data)):
    print(f"\nApplicant {i + 1} - Risk: {probabilities[i][1]*100:.1f}%")
    print("-" * 60)

    # Get top 5 features for this applicant
    applicant_shap = pd.DataFrame({
        'Feature': FEATURE_NAMES,
        'SHAP_Value': shap_values_risk[i],
        'Feature_Value': X_scaled[i]
    })
    applicant_shap['Abs_SHAP'] = np.abs(applicant_shap['SHAP_Value'])
    top_features = applicant_shap.nlargest(5, 'Abs_SHAP')

    print("Top 5 factors influencing this decision:")
    for idx, row in top_features.iterrows():
        direction = "increases" if row['SHAP_Value'] > 0 else "decreases"
        print(f"  • {row['Feature']:20s} {direction:9s} risk (impact: {abs(row['SHAP_Value']):.3f})")

print("\n" + "="*80)
print("Analysis Complete!")
print("="*80)
print("\nInterpretation Guide:")
print("- Positive SHAP values (red) indicate features that INCREASE default risk")
print("- Negative SHAP values (blue) indicate features that DECREASE default risk")
print("- Larger absolute values = stronger impact on prediction")
print("- The waterfall plot shows how each feature pushes prediction from base rate")
print("\nAll visualizations have been saved to the current directory.")

"""
Credit Risk Prediction with SHAP Explanations
Uses the Alfazril/credit-risk-prediction ensemble model from Hugging Face
and explains predictions with SHAP visualizations.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap
from huggingface_hub import hf_hub_download
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)

print("="*80)
print("Credit Risk Prediction System with SHAP Explanations")
print("="*80)

FEATURE_NAMES = [
    'Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
    'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio',
    'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
    'HasDependents', 'LoanPurpose', 'HasCoSigner'
]

# --- Load or create model ---
print("\nDownloading model from Hugging Face...")
try:
    model_path = hf_hub_download(
        repo_id="Alfazril/credit-risk-prediction",
        filename="credit_risk_xgboost_model.pkl"
    )
    print(f"Model downloaded successfully!")
except Exception as e:
    print(f"Could not download model file: {e}")
    print("Creating synthetic model for demonstration...\n")

    # Synthetic model for demonstration
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    scaler = StandardScaler()

    np.random.seed(42)
    n_samples = 1000
    X_synthetic = np.random.randn(n_samples, len(FEATURE_NAMES))
    y_synthetic = ((X_synthetic[:, 2] > 0.5) |
                   (X_synthetic[:, 8] > 0.7) |
                   (X_synthetic[:, 3] < -0.5)).astype(int)
    X_synthetic_scaled = scaler.fit_transform(X_synthetic)
    model.fit(X_synthetic_scaled, y_synthetic)
    print("Synthetic model created and trained.")

# --- Sample data ---
sample_data = pd.DataFrame([
    {'Age': 35, 'Income': 75000, 'LoanAmount': 25000, 'CreditScore': 720,
     'MonthsEmployed': 48, 'NumCreditLines': 5, 'InterestRate': 6.5,
     'LoanTerm': 60, 'DTIRatio': 0.35, 'Education': 1, 'EmploymentType': 1,
     'MaritalStatus': 1, 'HasMortgage': 1, 'HasDependents': 1,
     'LoanPurpose': 2, 'HasCoSigner': 0},
    {'Age': 28, 'Income': 45000, 'LoanAmount': 35000, 'CreditScore': 650,
     'MonthsEmployed': 24, 'NumCreditLines': 3, 'InterestRate': 9.5,
     'LoanTerm': 72, 'DTIRatio': 0.55, 'Education': 0, 'EmploymentType': 0,
     'MaritalStatus': 0, 'HasMortgage': 0, 'HasDependents': 0,
     'LoanPurpose': 1, 'HasCoSigner': 0},
    {'Age': 45, 'Income': 120000, 'LoanAmount': 15000, 'CreditScore': 800,
     'MonthsEmployed': 120, 'NumCreditLines': 8, 'InterestRate': 4.5,
     'LoanTerm': 36, 'DTIRatio': 0.15, 'Education': 2, 'EmploymentType': 1,
     'MaritalStatus': 1, 'HasMortgage': 1, 'HasDependents': 1,
     'LoanPurpose': 0, 'HasCoSigner': 0},
    {'Age': 32, 'Income': 60000, 'LoanAmount': 40000, 'CreditScore': 580,
     'MonthsEmployed': 18, 'NumCreditLines': 2, 'InterestRate': 12.5,
     'LoanTerm': 84, 'DTIRatio': 0.65, 'Education': 1, 'EmploymentType': 0,
     'MaritalStatus': 0, 'HasMortgage': 0, 'HasDependents': 1,
     'LoanPurpose': 3, 'HasCoSigner': 1},
    {'Age': 50, 'Income': 95000, 'LoanAmount': 20000, 'CreditScore': 750,
     'MonthsEmployed': 180, 'NumCreditLines': 6, 'InterestRate': 5.5,
     'LoanTerm': 48, 'DTIRatio': 0.25, 'Education': 2, 'EmploymentType': 1,
     'MaritalStatus': 1, 'HasMortgage': 1, 'HasDependents': 0,
     'LoanPurpose': 2, 'HasCoSigner': 0}
])

# --- Scale features ---
X_scaled = scaler.transform(sample_data.values)

# --- Make predictions ---
predictions = model.predict(X_scaled)
probabilities = model.predict_proba(X_scaled)

for idx, (pred, prob) in enumerate(zip(predictions, probabilities)):
    risk_prob = prob[1] * 100
    if risk_prob < 30:
        risk_level = "LOW RISK"
    elif risk_prob < 60:
        risk_level = "MEDIUM RISK"
    else:
        risk_level = "HIGH RISK"
    print(f"Applicant {idx+1}: {risk_prob:.1f}% risk, Classification: {risk_level}, Decision: {'APPROVED' if pred==0 else 'DENIED'}")

# --- SHAP Analysis ---
print("\nInitializing SHAP explainer...")
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_scaled)

# --- Robust handling of shapes ---
if isinstance(shap_values, list):
    shap_values_risk = shap_values[1]  # Positive class
else:
    shap_values_risk = shap_values

shap_values_risk = np.asarray(shap_values_risk, dtype=float)
print("Debug: SHAP values shape before check:", shap_values_risk.shape)

if shap_values_risk.ndim == 3:
    print("Debug: Detected 3D SHAP array, slicing class dimension...")
    shap_values_risk = shap_values_risk[:, :, 1]

print("Debug: SHAP values shape after fix:", shap_values_risk.shape)

# --- Feature importance ---
mean_abs_shap = np.mean(np.abs(shap_values_risk), axis=0).ravel()
feature_importance_df = pd.DataFrame({
    'Feature': FEATURE_NAMES,
    'Mean_Abs_SHAP': mean_abs_shap
}).sort_values('Mean_Abs_SHAP', ascending=False)

# --- SHAP visualizations ---
shap.summary_plot(shap_values_risk, X_scaled, feature_names=FEATURE_NAMES, show=False)
plt.savefig('shap_summary_plot.png', dpi=150, bbox_inches='tight')
plt.close()

shap.summary_plot(shap_values_risk, X_scaled, feature_names=FEATURE_NAMES, plot_type="bar", show=False)
plt.savefig('shap_importance_plot.png', dpi=150, bbox_inches='tight')
plt.close()

# Waterfall plot for first applicant
expected_value = explainer.expected_value
if isinstance(expected_value, list):
    expected_value = expected_value[1] if len(expected_value) > 1 else expected_value[0]
shap.waterfall_plot(
    shap.Explanation(
        values=shap_values_risk[0].ravel(),
        base_values=expected_value,
        data=X_scaled[0].ravel(),
        feature_names=FEATURE_NAMES
    ),
    show=False
)
plt.savefig('shap_waterfall_applicant1.png', dpi=150, bbox_inches='tight')
plt.close()

# Dependence plots for top 2 features
top_features_idx = np.argsort(mean_abs_shap)[-2:]
top_features_idx = [int(i) for i in top_features_idx]
for feat_idx in top_features_idx:
    try:
        shap.dependence_plot(
            feat_idx,
            shap_values_risk,
            X_scaled,
            feature_names=FEATURE_NAMES,
            show=False,
            interaction_index=None
        )
        plt.savefig(f'shap_dependence_{FEATURE_NAMES[feat_idx]}.png', dpi=150, bbox_inches='tight')
        plt.close()
    except Exception as e:
        print(f"Could not generate dependence plot for {FEATURE_NAMES[feat_idx]}: {e}")

# --- Individual applicant analysis ---
for i in range(len(sample_data)):
    applicant_shap = pd.DataFrame({
        'Feature': FEATURE_NAMES,
        'SHAP_Value': shap_values_risk[i].ravel(),
        'Feature_Value': X_scaled[i].ravel()
    })
    applicant_shap['Abs_SHAP'] = np.abs(applicant_shap['SHAP_Value'])
    top_features = applicant_shap.nlargest(5, 'Abs_SHAP')
    print(f"\nApplicant {i+1} - Risk: {probabilities[i][1]*100:.1f}%")
    print("Top 5 factors influencing this decision:")
    for _, row in top_features.iterrows():
        direction = "increases" if row['SHAP_Value'] > 0 else "decreases"
        print(f"  • {row['Feature']:20s} {direction:9s} risk (impact: {abs(row['SHAP_Value']):.3f})")

from huggingface_hub import list_repo_files
print(list_repo_files("Alfazril/credit-risk-prediction"))

preprocess_path = hf_hub_download(
    repo_id="Alfazril/credit-risk-prediction",
    filename="preprocessing_artifacts.pkl"
)

# Try joblib first, then pickle
try:
    preprocessing = joblib.load(preprocess_path)
    print("Preprocessing artifacts loaded with joblib.")
except Exception:
    with open(preprocess_path, "rb") as f:
        preprocessing = pickle.load(f)
    print("Preprocessing artifacts loaded with pickle.")

print("Debug: preprocessing type:", type(preprocessing))

if isinstance(preprocessing, dict):
    for k, v in preprocessing.items():
        print(f"\nKey: {k}")
        print("Type:", type(v))

        if hasattr(v, "get_feature_names_out"):
            names = v.get_feature_names_out()
            print(f"  Features ({len(names)}):")
            for f in names:
                print("   ", f)

names

import numpy as np
import pandas as pd

# Number of samples
N = 5

# Base raw-ish values
person_age = np.array([25, 35, 45, 60, 75])
person_income = np.array([35000, 60000, 90000, 70000, 50000])
person_emp_length = np.array([2, 8, 15, 20, 30])
loan_amnt = np.array([5000, 12000, 20000, 15000, 8000])
loan_int_rate = np.array([11.5, 9.2, 7.8, 8.5, 10.1])
cb_person_cred_hist_length = np.array([3, 10, 20, 30, 40])

# Derived numeric features
loan_percent_income = loan_amnt / person_income
income_to_age_ratio = person_income / person_age
loan_to_income_ratio = loan_amnt / person_income
credit_utilization = np.array([0.45, 0.35, 0.25, 0.30, 0.40])

# Logs (safe)
person_income_log = np.log1p(person_income)
loan_amnt_log = np.log1p(loan_amnt)

# Encoded ordinal features (reasonable ranges)
grade_risk_score = np.array([3, 2, 1, 2, 3])
combined_risk_score = np.array([0.65, 0.45, 0.30, 0.40, 0.55])
loan_grade_encoded = np.array([2, 1, 0, 1, 2])
employment_stability_encoded = np.array([1, 2, 3, 3, 4])
debt_to_income_category_encoded = np.array([2, 1, 0, 1, 2])
income_category_encoded = np.array([1, 2, 3, 2, 1])
credit_history_category_encoded = np.array([1, 2, 3, 3, 4])
loan_intent_target_encoded = np.array([0, 1, 0, 1, 0])

# One-hot: home ownership (exactly one per row)
home_ownership = np.array([
    [1, 0, 0],  # OTHER
    [0, 1, 0],  # OWN
    [0, 0, 1],  # RENT
    [0, 1, 0],
    [0, 0, 1]
])

# One-hot: default on file
cb_person_default_on_file_Y = np.array([0, 0, 1, 0, 1])

# One-hot: age groups (exactly one per row)
age_groups = np.array([
    [1, 0, 0, 0, 0],  # Millennial
    [0, 1, 0, 0, 0],  # Gen X
    [0, 0, 1, 0, 0],  # Boomer
    [0, 0, 0, 1, 0],  # Senior
    [0, 0, 0, 0, 1],  # Elder
])

# Assemble DataFrame
sample_data = pd.DataFrame({
    "person_age": person_age,
    "person_income": person_income,
    "person_emp_length": person_emp_length,
    "loan_amnt": loan_amnt,
    "loan_int_rate": loan_int_rate,
    "loan_percent_income": loan_percent_income,
    "cb_person_cred_hist_length": cb_person_cred_hist_length,
    "grade_risk_score": grade_risk_score,
    "combined_risk_score": combined_risk_score,
    "income_to_age_ratio": income_to_age_ratio,
    "loan_to_income_ratio": loan_to_income_ratio,
    "credit_utilization": credit_utilization,
    "person_income_log": person_income_log,
    "loan_amnt_log": loan_amnt_log,
    "loan_grade_encoded": loan_grade_encoded,
    "employment_stability_encoded": employment_stability_encoded,
    "debt_to_income_category_encoded": debt_to_income_category_encoded,
    "income_category_encoded": income_category_encoded,
    "credit_history_category_encoded": credit_history_category_encoded,
    "loan_intent_target_encoded": loan_intent_target_encoded,
    "person_home_ownership_OTHER": home_ownership[:, 0],
    "person_home_ownership_OWN": home_ownership[:, 1],
    "person_home_ownership_RENT": home_ownership[:, 2],
    "cb_person_default_on_file_Y": cb_person_default_on_file_Y,
    "age_group_Millennial": age_groups[:, 0],
    "age_group_Gen X": age_groups[:, 1],
    "age_group_Boomer": age_groups[:, 2],
    "age_group_Senior": age_groups[:, 3],
    "age_group_Elder": age_groups[:, 4],
})

# Final safety check
assert sample_data.shape[1] == 29

"""
Credit Risk Prediction with SHAP Explanations
Uses the Alfazril/credit-risk-prediction ensemble model from Hugging Face
and explains predictions with SHAP visualizations.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import shap
from huggingface_hub import hf_hub_download
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)

print("="*80)
print("Credit Risk Prediction System with SHAP Explanations")
print("="*80)

FEATURE_NAMES = names

# --- Load or create model ---
print("\nDownloading model from Hugging Face...")

model = None
scaler = None
model_downloaded = False

try:
    model_path = hf_hub_download(
        repo_id="Alfazril/credit-risk-prediction",
        filename="credit_risk_xgboost_model.pkl"
    )
    print(f"Model file downloaded to: {model_path}")

    # Try joblib first
    try:
        import joblib
        model = joblib.load(model_path)
        print("Model loaded with joblib.")
    except Exception:
        # Fall back to pickle
        import pickle
        with open(model_path, "rb") as f:
            model = pickle.load(f)
        print("Model loaded with pickle.")

    model_downloaded = True

    print("Model type:", type(model))

    if hasattr(model, "n_features_in_"):
        print("Model expects n_features:", model.n_features_in_)

    if hasattr(model, "feature_names_in_"):
        print("Model feature names:", model.feature_names_in_)

except Exception as e:
    print(f"Could not download or load model: {e}")
    print("Falling back to synthetic model...\n")

    model_downloaded = False

if not model_downloaded:
    # Synthetic model for demonstration
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    scaler = StandardScaler()

    np.random.seed(42)
    n_samples = 1000
    X_synthetic = np.random.randn(n_samples, len(FEATURE_NAMES))
    y_synthetic = ((X_synthetic[:, 2] > 0.5) |
                   (X_synthetic[:, 8] > 0.7) |
                   (X_synthetic[:, 3] < -0.5)).astype(int)
    X_synthetic_scaled = scaler.fit_transform(X_synthetic)
    model.fit(X_synthetic_scaled, y_synthetic)
    print("Synthetic model created and trained.")

# --- Scale features if needed ---
if model_downloaded:
    # Assume downloaded model handles preprocessing
    X_scaled = sample_data.values
else:
    X_scaled = scaler.transform(sample_data.values)

# --- Make predictions ---
predictions = model.predict(X_scaled)
probabilities = model.predict_proba(X_scaled)

for idx, (pred, prob) in enumerate(zip(predictions, probabilities)):
    risk_prob = prob[1] * 100
    if risk_prob < 30:
        risk_level = "LOW RISK"
    elif risk_prob < 60:
        risk_level = "MEDIUM RISK"
    else:
        risk_level = "HIGH RISK"
    print(f"Applicant {idx+1}: {risk_prob:.1f}% risk, Classification: {risk_level}, Decision: {'APPROVED' if pred==0 else 'DENIED'}")

# --- SHAP Analysis ---
print("\nInitializing SHAP explainer...")
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_scaled)

# --- Robust handling of shapes ---
if isinstance(shap_values, list):
    shap_values_risk = shap_values[1]  # Positive class
else:
    shap_values_risk = shap_values

shap_values_risk = np.asarray(shap_values_risk, dtype=float)
print("Debug: SHAP values shape before check:", shap_values_risk.shape)

if shap_values_risk.ndim == 3:
    print("Debug: Detected 3D SHAP array, slicing class dimension...")
    shap_values_risk = shap_values_risk[:, :, 1]

print("Debug: SHAP values shape after fix:", shap_values_risk.shape)

# --- Feature importance ---
mean_abs_shap = np.mean(np.abs(shap_values_risk), axis=0).ravel()
feature_importance_df = pd.DataFrame({
    'Feature': FEATURE_NAMES,
    'Mean_Abs_SHAP': mean_abs_shap
}).sort_values('Mean_Abs_SHAP', ascending=False)

# --- SHAP visualizations ---
shap.summary_plot(shap_values_risk, X_scaled, feature_names=FEATURE_NAMES, show=False)
plt.savefig('shap_summary_plot.png', dpi=150, bbox_inches='tight')
plt.close()

shap.summary_plot(shap_values_risk, X_scaled, feature_names=FEATURE_NAMES, plot_type="bar", show=False)
plt.savefig('shap_importance_plot.png', dpi=150, bbox_inches='tight')
plt.close()

# Waterfall plot for first applicant
expected_value = explainer.expected_value
if isinstance(expected_value, list):
    expected_value = expected_value[1] if len(expected_value) > 1 else expected_value[0]
shap.waterfall_plot(
    shap.Explanation(
        values=shap_values_risk[0].ravel(),
        base_values=expected_value,
        data=X_scaled[0].ravel(),
        feature_names=FEATURE_NAMES
    ),
    show=False
)
plt.savefig('shap_waterfall_applicant1.png', dpi=150, bbox_inches='tight')
plt.close()

# Dependence plots for top 2 features
top_features_idx = np.argsort(mean_abs_shap)[-2:]
top_features_idx = [int(i) for i in top_features_idx]
for feat_idx in top_features_idx:
    try:
        shap.dependence_plot(
            feat_idx,
            shap_values_risk,
            X_scaled,
            feature_names=FEATURE_NAMES,
            show=False,
            interaction_index=None
        )
        plt.savefig(f'shap_dependence_{FEATURE_NAMES[feat_idx]}.png', dpi=150, bbox_inches='tight')
        plt.close()
    except Exception as e:
        print(f"Could not generate dependence plot for {FEATURE_NAMES[feat_idx]}: {e}")

# --- Individual applicant analysis ---
for i in range(len(sample_data)):
    applicant_shap = pd.DataFrame({
        'Feature': FEATURE_NAMES,
        'SHAP_Value': shap_values_risk[i].ravel(),
        'Feature_Value': X_scaled[i].ravel()
    })
    applicant_shap['Abs_SHAP'] = np.abs(applicant_shap['SHAP_Value'])
    top_features = applicant_shap.nlargest(5, 'Abs_SHAP')
    print(f"\nApplicant {i+1} - Risk: {probabilities[i][1]*100:.1f}%")
    print("Top 5 factors influencing this decision:")
    for _, row in top_features.iterrows():
        direction = "increases" if row['SHAP_Value'] > 0 else "decreases"
        print(f"  • {row['Feature']:20s} {direction:9s} risk (impact: {abs(row['SHAP_Value']):.3f})")

